// AUTO-GENERATED by scripts/build-images.mjs — do not edit by hand.
// Run `npm run images` to regenerate after adding new photos.

import beachSunset1640Avif from '../Assets/optimized/beach-sunset1-640.avif';
import beachSunset1640Webp from '../Assets/optimized/beach-sunset1-640.webp';
import beachSunset1640Jpg  from '../Assets/optimized/beach-sunset1-640.jpg';
import coastalCity1640Avif from '../Assets/optimized/coastal-city1-640.avif';
import coastalCity1640Webp from '../Assets/optimized/coastal-city1-640.webp';
import coastalCity1640Jpg  from '../Assets/optimized/coastal-city1-640.jpg';
import joytripSunrisePhoto640Avif from '../Assets/optimized/joytrip-sunrise-photo-640.avif';
import joytripSunrisePhoto640Webp from '../Assets/optimized/joytrip-sunrise-photo-640.webp';
import joytripSunrisePhoto640Jpg  from '../Assets/optimized/joytrip-sunrise-photo-640.jpg';
import joytripSunrisePhoto1024Avif from '../Assets/optimized/joytrip-sunrise-photo-1024.avif';
import joytripSunrisePhoto1024Webp from '../Assets/optimized/joytrip-sunrise-photo-1024.webp';
import joytripSunrisePhoto1024Jpg  from '../Assets/optimized/joytrip-sunrise-photo-1024.jpg';
import joytripSunrisePhoto1600Avif from '../Assets/optimized/joytrip-sunrise-photo-1600.avif';
import joytripSunrisePhoto1600Webp from '../Assets/optimized/joytrip-sunrise-photo-1600.webp';
import joytripSunrisePhoto1600Jpg  from '../Assets/optimized/joytrip-sunrise-photo-1600.jpg';
import joytripSunrisePhoto2400Avif from '../Assets/optimized/joytrip-sunrise-photo-2400.avif';
import joytripSunrisePhoto2400Webp from '../Assets/optimized/joytrip-sunrise-photo-2400.webp';
import joytripSunrisePhoto2400Jpg  from '../Assets/optimized/joytrip-sunrise-photo-2400.jpg';
import joytripSunsetPhoto640Avif from '../Assets/optimized/joytrip-sunset-photo-640.avif';
import joytripSunsetPhoto640Webp from '../Assets/optimized/joytrip-sunset-photo-640.webp';
import joytripSunsetPhoto640Jpg  from '../Assets/optimized/joytrip-sunset-photo-640.jpg';
import joytripSunsetPhoto1024Avif from '../Assets/optimized/joytrip-sunset-photo-1024.avif';
import joytripSunsetPhoto1024Webp from '../Assets/optimized/joytrip-sunset-photo-1024.webp';
import joytripSunsetPhoto1024Jpg  from '../Assets/optimized/joytrip-sunset-photo-1024.jpg';
import joytripSunsetPhoto1600Avif from '../Assets/optimized/joytrip-sunset-photo-1600.avif';
import joytripSunsetPhoto1600Webp from '../Assets/optimized/joytrip-sunset-photo-1600.webp';
import joytripSunsetPhoto1600Jpg  from '../Assets/optimized/joytrip-sunset-photo-1600.jpg';
import joytripSunsetPhoto2400Avif from '../Assets/optimized/joytrip-sunset-photo-2400.avif';
import joytripSunsetPhoto2400Webp from '../Assets/optimized/joytrip-sunset-photo-2400.webp';
import joytripSunsetPhoto2400Jpg  from '../Assets/optimized/joytrip-sunset-photo-2400.jpg';
import lauderdaleSunriseCorn640Avif from '../Assets/optimized/lauderdale-sunrise-corn-640.avif';
import lauderdaleSunriseCorn640Webp from '../Assets/optimized/lauderdale-sunrise-corn-640.webp';
import lauderdaleSunriseCorn640Jpg  from '../Assets/optimized/lauderdale-sunrise-corn-640.jpg';
import lauderdaleSunriseCorn1024Avif from '../Assets/optimized/lauderdale-sunrise-corn-1024.avif';
import lauderdaleSunriseCorn1024Webp from '../Assets/optimized/lauderdale-sunrise-corn-1024.webp';
import lauderdaleSunriseCorn1024Jpg  from '../Assets/optimized/lauderdale-sunrise-corn-1024.jpg';
import lauderdaleSunriseCorn1600Avif from '../Assets/optimized/lauderdale-sunrise-corn-1600.avif';
import lauderdaleSunriseCorn1600Webp from '../Assets/optimized/lauderdale-sunrise-corn-1600.webp';
import lauderdaleSunriseCorn1600Jpg  from '../Assets/optimized/lauderdale-sunrise-corn-1600.jpg';
import lauderdaleSunriseCorn2400Avif from '../Assets/optimized/lauderdale-sunrise-corn-2400.avif';
import lauderdaleSunriseCorn2400Webp from '../Assets/optimized/lauderdale-sunrise-corn-2400.webp';
import lauderdaleSunriseCorn2400Jpg  from '../Assets/optimized/lauderdale-sunrise-corn-2400.jpg';
import vueFullBand640Avif from '../Assets/optimized/vue-full-band-640.avif';
import vueFullBand640Webp from '../Assets/optimized/vue-full-band-640.webp';
import vueFullBand640Jpg  from '../Assets/optimized/vue-full-band-640.jpg';
import vueFullBand1024Avif from '../Assets/optimized/vue-full-band-1024.avif';
import vueFullBand1024Webp from '../Assets/optimized/vue-full-band-1024.webp';
import vueFullBand1024Jpg  from '../Assets/optimized/vue-full-band-1024.jpg';
import vueFullBand1600Avif from '../Assets/optimized/vue-full-band-1600.avif';
import vueFullBand1600Webp from '../Assets/optimized/vue-full-band-1600.webp';
import vueFullBand1600Jpg  from '../Assets/optimized/vue-full-band-1600.jpg';
import vueFullBand2400Avif from '../Assets/optimized/vue-full-band-2400.avif';
import vueFullBand2400Webp from '../Assets/optimized/vue-full-band-2400.webp';
import vueFullBand2400Jpg  from '../Assets/optimized/vue-full-band-2400.jpg';

export const imageManifest = Object.freeze({
  'beach-sunset1': {
    avif: [beachSunset1640Avif],
    webp: [beachSunset1640Webp],
    jpg:  [beachSunset1640Jpg],
    widths: [640],
    naturalWidth: 640,
    naturalHeight: 427,
  },
  'coastal-city1': {
    avif: [coastalCity1640Avif],
    webp: [coastalCity1640Webp],
    jpg:  [coastalCity1640Jpg],
    widths: [640],
    naturalWidth: 940,
    naturalHeight: 625,
  },
  'joytrip-sunrise-photo': {
    avif: [joytripSunrisePhoto640Avif, joytripSunrisePhoto1024Avif, joytripSunrisePhoto1600Avif, joytripSunrisePhoto2400Avif],
    webp: [joytripSunrisePhoto640Webp, joytripSunrisePhoto1024Webp, joytripSunrisePhoto1600Webp, joytripSunrisePhoto2400Webp],
    jpg:  [joytripSunrisePhoto640Jpg, joytripSunrisePhoto1024Jpg, joytripSunrisePhoto1600Jpg, joytripSunrisePhoto2400Jpg],
    widths: [640, 1024, 1600, 2400],
    naturalWidth: 2629,
    naturalHeight: 1497,
  },
  'joytrip-sunset-photo': {
    avif: [joytripSunsetPhoto640Avif, joytripSunsetPhoto1024Avif, joytripSunsetPhoto1600Avif, joytripSunsetPhoto2400Avif],
    webp: [joytripSunsetPhoto640Webp, joytripSunsetPhoto1024Webp, joytripSunsetPhoto1600Webp, joytripSunsetPhoto2400Webp],
    jpg:  [joytripSunsetPhoto640Jpg, joytripSunsetPhoto1024Jpg, joytripSunsetPhoto1600Jpg, joytripSunsetPhoto2400Jpg],
    widths: [640, 1024, 1600, 2400],
    naturalWidth: 4240,
    naturalHeight: 2385,
  },
  'lauderdale-sunrise-corn': {
    avif: [lauderdaleSunriseCorn640Avif, lauderdaleSunriseCorn1024Avif, lauderdaleSunriseCorn1600Avif, lauderdaleSunriseCorn2400Avif],
    webp: [lauderdaleSunriseCorn640Webp, lauderdaleSunriseCorn1024Webp, lauderdaleSunriseCorn1600Webp, lauderdaleSunriseCorn2400Webp],
    jpg:  [lauderdaleSunriseCorn640Jpg, lauderdaleSunriseCorn1024Jpg, lauderdaleSunriseCorn1600Jpg, lauderdaleSunriseCorn2400Jpg],
    widths: [640, 1024, 1600, 2400],
    naturalWidth: 2843,
    naturalHeight: 1518,
  },
  'vue-full-band': {
    avif: [vueFullBand640Avif, vueFullBand1024Avif, vueFullBand1600Avif, vueFullBand2400Avif],
    webp: [vueFullBand640Webp, vueFullBand1024Webp, vueFullBand1600Webp, vueFullBand2400Webp],
    jpg:  [vueFullBand640Jpg, vueFullBand1024Jpg, vueFullBand1600Jpg, vueFullBand2400Jpg],
    widths: [640, 1024, 1600, 2400],
    naturalWidth: 2810,
    naturalHeight: 2720,
  },
});
